---
title: "R Test 1"
subtitle: "Mock exam"  
author: 
  - "AJ Smit"
institute: "University of the Western Cape"
date: '2021/04/21 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "../private/default-fonts.css"
      - ki
      - "../private/uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include=FALSE, echo=FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

# Instructions
A. Make sure that all formal inferential tests are preceded by the appropriate tests for the assumptions, i.e., state the assumptions, state the tests and mention their corresponding H0 (or explain the principle behind a graphical method), explain the findings, and justify your selection of the appropriate inferential test (e.g. *t*-test, ANOVA, etc.) that you will use.

B. Produce full R scripts, including the meta-information at the top (name, date, purpose, etc.). Include comments explaining the purpose of the various tests/sections as necessary.

C. Pay attention to formatting. 10% will be allocated to the appearance of the script, including considerations of aspects of the tidiness of the file, the use of appropriate headings, and adherence to code conventions (e.g. spacing etc.).

---
# Chromosomal Effects of Mercury-Contaminated Fish Consumption

Package **coin**, dataset `mercuryfish`: The mercury level in blood, the proportion of cells with abnormalities, and the proportion of cells with chromosome aberrations in consumers of mercury-contaminated fish and a control group.

## Question 1
- Demonstrate your working knowledge of *t*-tests. Using only one of the response variables,
    - state the 'flavour' of *t*-test you chose to use, and justify its use,
    - provide a suitable H0,
    - undertake the analysis,
    - describe the results.

---
## Question 2
- Demonstrate your working knowledge of a simple linear regression. Using the appropriate data for the independent variable and *one* of the response variables, 
    - provide the H0,
    - undertake a separate analysis for each of the treatment groups,
    - describe the results,
    - produce a graph suitable for this kind of analysis.

---
# Malignant Glioma Pilot Study

Package **coin**, dataset `glioma`: A non-randomized pilot study on malignant glioma patients with pretargeted adjuvant radioimmunotherapy using yttrium-90-biotin.

## Question 3
- Do `sex` and `group` interact to affect survival time (`time`)?
    - What test would you use, and why?
    - State the H0.
    - Undertake the analysis.
    - Explain the findings.
    - Provide a graphical summary of the results.
    
---
## Question 4
- Do `age` and `histology` interact to affect survival time (`time`)?
    - What test would you use, and why?
    - State the H0.
    - Undertake the analysis.
    - Explain the findings.
    - Provide a graphical summary of the results.
    
---
# The Effect of Vitamin C on Tooth Growth in Guinea Pigs

Package **datasets**, dataset `ToothGrowth`: The response is the length of odontoblasts (cells responsible for tooth growth) in 60 guinea pigs. Each animal received one of three dose levels of vitamin C (0.5, 1, and 2 mg/day) by one of two delivery methods, orange juice or ascorbic acid (a form of vitamin C and coded as `VC`).

## Question 5
- Explain what the most appropriate statistical test is to use for analysing this dataset.
    - Provide the H0.
    - Undertake the analysis.
    - Describe the findings.
    - Create a box-and-whisker plot as graphical summary of your findings.

---
# Risk Factors Associated with Low Infant Birth Weight

Package **MASS**, dataset `birthwt`: The birthwt data frame has 189 rows and 10 columns. The data were collected at Baystate Medical Center, Springfield, Mass during 1986.

## Question 6
- State three H0s and test them. Make sure one of the tests makes use of the 95% confidence interval approach rather than a formal methodology. Include graphical summaries for each of the three null hypothesis.

