remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
show_downloads: true
markdown: kramdown
title: Basic Statistics in R
description: By Prof. AJ Smit, BCB, UWC

